- .github/workflows/deploy-website-mintlify.yml
> Add workflow file to deploy mintlify docs

- .github/workflows/deploy-website-mintlify.yml
> Update mintlify deploy workflow file

- .github/workflows/deploy-website-mintlify.yml
> Do not copy gitignore and other temp files to the docs directory

- website/mint.json
- website/process_notebooks.py
- website/snippets/data/NotebooksMetadata.mdx
> Fix notebook parsing errors

- website/mint-style.css
- website/snippets/components/GalleryPage.mdx
> Remove images and select box from the application gallery page

- .github/workflows/deploy-website-mintlify.yml
- website/mint.json
- website/process_api_reference.py
> Add api docs

- website/process_api_reference.py
> Sort the API reference navigation

- website/docs/tutorial/what-next.mdx
- website/process_notebooks.py
> Remove duplicate headers

- website/docs/topics/llm-caching.mdx
- website/docs/topics/llm-observability.mdx
> Fix duplicate headers

- website/process_notebooks.py
- website/snippets/data/NotebooksMetadata.mdx
> Fix images path

- website/mint.json
> Add og image tag

- website/process_notebooks.py
> Fix broken image path

- .github/workflows/deploy-website.yml
> Add debugging messages

- .github/workflows/deploy-website.yml
> Update publish directory path

- .github/workflows/deploy-website.yml
> Fix publish dir path

- website/docs/Getting-Started.mdx
- website/mint.json
- website/static/img/cover.png
> Add cover image

- website/mint.json
> Use hosted social image

- website/mint.json
> Test social image

- website/mint.json
> Update social image

- website/mint.json
> Update social img

- .github/workflows/deploy-website.yml
> Update redirect URL

- website/mint.json
> Reorder blog posts

- website/blog/2024-12-02-ReasoningAgent2/index.mdx
- website/blog/2024-12-06-FalkorDB-Structured/index.mdx
- website/blog/2024-12-20-RealtimeAgent/index.mdx
- website/blog/2024-12-20-Reasoning-Update/index.mdx
- website/blog/2024-12-20-Tools-interoperability/index.mdx
- website/mint-style.css
> Add authors information

- website/mint.json
> Remove duplicate entry from navigation

- .github/workflows/deploy-website.yml
> Fix 404 redirection

- website/mint-script.js
- website/mint-style.css
> Fix Header Case in API Reference to Match Object Names

- .github/workflows/deploy-website-mintlify.yml
- .github/workflows/docs-check-broken-links.yml
> Do not run broken link check for pull requests

- .devcontainer/dev/Dockerfile
- .muffet-excluded-links.txt
- autogen/agentchat/chat.py
- autogen/agentchat/conversable_agent.py
- autogen/agentchat/user_proxy_agent.py
- autogen/oai/gemini.py
- notebook/agentchat_agentops.ipynb
- notebook/agentchat_function_call.ipynb
- notebook/agentchat_function_call_currency_calculator.ipynb
- notebook/agentchat_graph_rag_neo4j.ipynb
- notebook/agentchat_human_feedback.ipynb
- scripts/broken-links-check.sh
- website/mint.json
- website/snippets/data/NotebooksMetadata.mdx
> Fix broken links

- website/snippets/components/GalleryPage.mdx
> Fix image path

- website/docs/Gallery.mdx
> Update application contribution guide

- notebook/agentchat_realtime_websocket.ipynb
- website/mint.json
- website/snippets/data/NotebooksMetadata.mdx
> Add missing frontmatter metadata to notebook

- notebook/agentchat_MathChat.ipynb
- notebook/agentchat_graph_rag_falkordb.ipynb
- notebook/config_loader_utility_functions.ipynb
- website/mint.json
- website/snippets/data/NotebooksMetadata.mdx
> Add front matter to notebooks

- .github/workflows/deploy-website-mintlify.yml
- website/process_notebooks.py
> [Docs] Fix tag filtering in examples section

- website/mint.json
- website/talks/2024-12-12/index.mdx
- website/talks/2024-12-19/index.mdx
> Fix docs build and update navigation

- .muffet-excluded-links.txt
> Add correct URL in muffet exclusion list

- test/website/test_process_api_reference.py
- test/website/test_process_notebooks.py
- website/process_api_reference.py
- website/process_notebooks.py
> Fix linting issues

- .github/workflows/deploy-website-mintlify.yml
> Update python version in workflow file

- .devcontainer/dev/Dockerfile
- .github/workflows/deploy-website-mintlify.yml
- notebook/agentchat_MathChat.ipynb
- pyproject.toml
- scripts/docs_build.sh
> Review fixes

- website/mint-json-template.json.jinja
> Fix file name in navigation

- .github/workflows/deploy-website.yml
- website/mkdocs/README.md
- website/mkdocs/mkdocs.yml
- website/mkdocs/templates/redirect.html
> Configure mkdocs versioning

- autogen/version.py
- website/mkdocs/docs/docs/home/home.md
> test-versioning

- .github/workflows/build-mkdocs.yml
> Deploy docs from 0.9 branch
